### ISSUE TITLE
在编译 golang 软件包时设置 GOPROXY 环境变量

### ISSUE THREAD

**Issue by yxd-ym** [lcpu-club/loongarch-packages#379]
观察到很多 golang 软件包都构建失败，可能需要在构建时使用

https://goproxy.io/

设置以下环境变量

```
GOPROXY=https://goproxy.io,direct
```

来获取依赖的库

**Comment by wszqkzqk** [comment]
No, we have additional processing for the network environment. The reason for the build failure is not the failure to download dependencies, but the adaptation problem.

In principle, we do not allow modifications that are not related to architectural repairs.

不，我们对网络环境有额外的处理，导致构建失败的原因并不是依赖下载失败，而是适配问题。

我们原则上不允许与架构修复无关的修改。

PS. 你可以在我们的仓库中检索以查看`go`包一般是如何修复的。

关于这个仓库维护什么内容，参见[贡献之前需要学习的基本概念](https://github.com/lcpu-club/loongarch-packages/wiki/Essential-Concepts-to-Learn-Before-Contributing)：

> loongarch-packages 只 用来存一些loong64架构特定的编译修复。
